"""
AI-powered changelog generation via GitHub Models.

Triggered on release creation. Fetches commits since the previous tag,
asks the model to write a structured changelog, then patches the release body.

Commit format expected: conventional commits (feat, fix, chore, docs, refactor...).
Falls back gracefully if commits don't follow the convention.

Required env vars:
  GITHUB_TOKEN  — built-in token (contents: write, models: read)
  REPO          — repository in owner/repo format
  TAG_NAME      — current release tag (e.g. v1.2.3)
  RELEASE_ID    — GitHub release ID (integer as string)
"""

from __future__ import annotations

import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
from github_models import DEFAULT_MODEL, chat, github_api

SYSTEM_PROMPT = """You are a technical writer generating a changelog for an IaC repository.

Given a list of git commits, write a clean, concise changelog in markdown.

Structure:
## What's changed

### Features
- ...

### Fixes
- ...

### Infrastructure & maintenance
- ...

Rules:
- Group commits by type (feat → Features, fix → Fixes, chore/refactor/docs → Infrastructure & maintenance)
- Skip merge commits and automated commits ([skip ci], chore: bump)
- Write each entry as a user-facing sentence, not a raw commit message
- If there are no commits in a category, omit that section entirely
- Keep it short — one line per commit, no padding
- Respond in French if more than half the commits are in French, otherwise English"""


def get_previous_tag(current_tag: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "tag", "--sort=-creatordate"],
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        print(f"git tag failed (exit {exc.returncode}): {exc.stderr}", file=sys.stderr)
        return None

    tags = [t.strip() for t in result.stdout.splitlines() if t.strip()]
    try:
        idx = tags.index(current_tag)
        return tags[idx + 1] if idx + 1 < len(tags) else None
    except ValueError:
        return None


def get_commits(from_ref: str | None, to_ref: str) -> str:
    ref_range = f"{from_ref}..{to_ref}" if from_ref else to_ref
    try:
        result = subprocess.run(
            ["git", "log", ref_range, "--pretty=format:%s", "--no-merges"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as exc:
        print(f"git log failed (exit {exc.returncode}): {exc.stderr}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    repo = os.environ["REPO"]
    tag_name = os.environ["TAG_NAME"]
    release_id = os.environ["RELEASE_ID"]

    previous_tag = get_previous_tag(tag_name)
    commits = get_commits(previous_tag, tag_name)

    if not commits:
        print("No commits found — skipping changelog generation.")
        return

    print(f"Generating changelog for {tag_name} ({commits.count(chr(10)) + 1} commits)")
    changelog = chat(
        system=SYSTEM_PROMPT,
        user=f"Tag: {tag_name}\nPrevious tag: {previous_tag or 'none (first release)'}\n\nCommits:\n{commits}",
        model=DEFAULT_MODEL,
        max_tokens=1000,
        temperature=0.3,
    )

    footer = f"\n\n---\n*Changelog generated by GitHub Models (`{DEFAULT_MODEL}`)*"
    try:
        github_api(
            f"/repos/{repo}/releases/{release_id}",
            method="PATCH",
            body={"body": changelog + footer},
        )
        print("Release notes updated.")
    except RuntimeError as exc:
        print(f"GitHub API error: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
